# Generated by Django 4.1.5 on 2023-03-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leave_available',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
