# Generated by Django 4.1.5 on 2023-03-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_employee_leave_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='employee_leave',
            old_name='employee',
            new_name='user',
        ),
    ]
