# Generated by Django 4.1.5 on 2023-03-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_employee_gender_alter_employee_leave_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
